databases:
  - name: inverse-staging-db
    plan: starter
  
services:
  - type: web
    name: inverse-staging
    env: go
    region: oregon
    buildCommand: ./render-build.sh
    startCommand: ./inverse
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inverse-staging-db
          property: connectionString
      - key: APP_ENV
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_USER
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: STABILITY_API_KEY
        sync: false
      - key: MAILGUN_DOMAIN
        sync: false
      - key: MAILGUN_API_KEY
        sync: false
      - key: INVERSE_FACTORY_ADDRESS
        sync: false
      - key: RPC_PROVIDER
        sync: false
      - key: POLYGON_RPC_PROVIDER
        sync: false
      - key: BASE_RPC_PROVIDER
        sync: false
      - key: AA_SERVER
        sync: false
      - key: API_BASE_URL
        sync: false
      - key: MIDJOURNEY_API_KEY
        sync: false
      - key: PRIVY_APP_ID
        sync: false
      - key: PRIVY_APP_SECRET
        sync: false
      - key: PRIVY_VERIFICATION_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false